// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PriceUIClient is the client API for PriceUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PriceUIClient interface {
	// ListEngineSpecs returns a list of Price Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (PriceUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type priceUIClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceUIClient(cc grpc.ClientConnInterface) PriceUIClient {
	return &priceUIClient{cc}
}

func (c *priceUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (PriceUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PriceUI_ServiceDesc.Streams[0], "/v1.PriceUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &priceUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PriceUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type priceUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *priceUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *priceUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.PriceUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceUIServer is the server API for PriceUI service.
// All implementations must embed UnimplementedPriceUIServer
// for forward compatibility
type PriceUIServer interface {
	// ListEngineSpecs returns a list of Price Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, PriceUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedPriceUIServer()
}

// UnimplementedPriceUIServer must be embedded to have forward compatible implementations.
type UnimplementedPriceUIServer struct {
}

func (UnimplementedPriceUIServer) ListEngineSpecs(*ListEngineSpecsRequest, PriceUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedPriceUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedPriceUIServer) mustEmbedUnimplementedPriceUIServer() {}

// UnsafePriceUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceUIServer will
// result in compilation errors.
type UnsafePriceUIServer interface {
	mustEmbedUnimplementedPriceUIServer()
}

func RegisterPriceUIServer(s grpc.ServiceRegistrar, srv PriceUIServer) {
	s.RegisterService(&PriceUI_ServiceDesc, srv)
}

func _PriceUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PriceUIServer).ListEngineSpecs(m, &priceUIListEngineSpecsServer{stream})
}

type PriceUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type priceUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *priceUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PriceUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PriceUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PriceUI_ServiceDesc is the grpc.ServiceDesc for PriceUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PriceUI",
	HandlerType: (*PriceUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _PriceUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _PriceUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "price-ui.proto",
}
